//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumBoard.ScrumboardService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScrumboardService.ScrumboardSoap")]
    public interface ScrumboardSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoryInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int StoryInsert(int sprintId, string externalId, int storyTypeId, int statusId, string description, int estimate, int backcolor, int x, int y, string tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoryUpdateDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void StoryUpdateDetails(int id, int sprintId, string externalId, int storyTypeId, int statusId, string description, int estimate, int backcolor, int x, int y, string tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoryUpdateStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void StoryUpdateStatus(int id, int statusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoryRemove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void StoryRemove(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoryGetByExternalId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Story StoryGetByExternalId(int sprintId, string externalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoryGetSprintStories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        Story[] StoryGetSprintStories(int sprintId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoryGetPanelStories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        Story[] StoryGetPanelStories(int sprintId, int storyTypeId, int statusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SprintInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        int SprintInsert(int layoutId, int teamId, string name, System.DateTime startDate, System.DateTime target);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SprintUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void SprintUpdate(int id, int layoutId, int teamId, string name, System.DateTime startDate, System.DateTime target);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SprintGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Sprint SprintGet(int sprintId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SprintSelectAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        Sprint[] SprintSelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SprintSelectByTeam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        Sprint[] SprintSelectByTeam(int teamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StateSelectAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        State[] StateSelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StateGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.State StateGet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoryTypeSelectAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        StoryType[] StoryTypeSelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoryTypeGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.StoryType StoryTypeGet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayoutSelectAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        Layout[] LayoutSelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayoutInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        int LayoutInsert(string name, int totalColumns, int totalRows, int fontSize, int storyWidth, int storyHeight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayoutUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void LayoutUpdate(int id, string name, int totalColumns, int totalRows, int fontSize, int storyWidth, int storyHeight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayoutGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Layout LayoutGet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayoutPanelSelectByLayout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        Panel[] LayoutPanelSelectByLayout(int layoutId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayoutPanelGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Panel LayoutPanelGet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayoutPanelInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        int LayoutPanelInsert(int layoutId, int stateId, string title, int storyTypeId, int column, int row, int height, int width);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayoutPanelUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void LayoutPanelUpdate(int id, int stateId, string title, int storyTypeId, int column, int row, int height, int width);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayoutPanelRemove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void LayoutPanelRemove(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamSelectAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        Team[] TeamSelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Team TeamGet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        int TeamInsert(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void TeamUpdate(int id, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamRemove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void TeamRemove(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamAssignMember", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void TeamAssignMember(int teamId, int teamMemberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamDeassignMember", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void TeamDeassignMember(int teamId, int teamMemberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamMemberSelectAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        TeamMember[] TeamMemberSelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamMemberSelectByTeam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        TeamMember[] TeamMemberSelectByTeam(int teamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamMemberGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.TeamMember TeamMemberGet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamMemberInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        int TeamMemberInsert(string name, string userName, string focusFactor, string availabilityFactor, string normalWorkingHours);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamMemberUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void TeamMemberUpdate(int id, string name, string userName, string focusFactor, string availabilityFactor, string normalWorkingHours);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamMemberRemove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void TeamMemberRemove(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamGetNonWorkingHours", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        NonWorkingHours[] TeamGetNonWorkingHours(int teamMemberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamGetNonWorkingHoursAtDay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        NonWorkingHours[] TeamGetNonWorkingHoursAtDay(int teamMemberId, System.DateTime day);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamInsertNonWorkingHours", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        int TeamInsertNonWorkingHours(int teamMemberId, System.DateTime day, string hours);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamUpdateNonWorkingHours", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void TeamUpdateNonWorkingHours(int id, int teamMemberId, System.DateTime day, string hours);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamRemoveNonWorkingHours", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void TeamRemoveNonWorkingHours(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TodoInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        int TodoInsert(int storyId, string description, int estimate, int backcolor, int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TodoUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void TodoUpdate(int id, int storyId, string description, int estimate, int backcolor, int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TodoRemove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void TodoRemove(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TodoGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Todo TodoGet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TodoSelect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        Todo[] TodoSelect(int storyId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Story : BO {
        
        private int idField;
        
        private string externalIdField;
        
        private int sprintIdField;
        
        private int storyTypeIdField;
        
        private string descriptionField;
        
        private int estimateField;
        
        private int statusIdField;
        
        private int xField;
        
        private int yField;
        
        private int backColorField;
        
        private string tagField;
        
        private System.DateTime closedDateField;
        
        private bool isBurndownEnabledField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ExternalId {
            get {
                return this.externalIdField;
            }
            set {
                this.externalIdField = value;
                this.RaisePropertyChanged("ExternalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int SprintId {
            get {
                return this.sprintIdField;
            }
            set {
                this.sprintIdField = value;
                this.RaisePropertyChanged("SprintId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int StoryTypeId {
            get {
                return this.storyTypeIdField;
            }
            set {
                this.storyTypeIdField = value;
                this.RaisePropertyChanged("StoryTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Estimate {
            get {
                return this.estimateField;
            }
            set {
                this.estimateField = value;
                this.RaisePropertyChanged("Estimate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int StatusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
                this.RaisePropertyChanged("StatusId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("X");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("Y");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int BackColor {
            get {
                return this.backColorField;
            }
            set {
                this.backColorField = value;
                this.RaisePropertyChanged("BackColor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("Tag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime ClosedDate {
            get {
                return this.closedDateField;
            }
            set {
                this.closedDateField = value;
                this.RaisePropertyChanged("ClosedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool IsBurndownEnabled {
            get {
                return this.isBurndownEnabledField;
            }
            set {
                this.isBurndownEnabledField = value;
                this.RaisePropertyChanged("IsBurndownEnabled");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Todo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NonWorkingHours))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TeamMember))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Team))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Panel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Layout))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StoryType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(State))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Sprint))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Story))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class BO : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Todo : BO {
        
        private int idField;
        
        private int storyIdField;
        
        private string descriptionField;
        
        private int estimateField;
        
        private int backColorField;
        
        private int xField;
        
        private int yField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int StoryId {
            get {
                return this.storyIdField;
            }
            set {
                this.storyIdField = value;
                this.RaisePropertyChanged("StoryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Estimate {
            get {
                return this.estimateField;
            }
            set {
                this.estimateField = value;
                this.RaisePropertyChanged("Estimate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int BackColor {
            get {
                return this.backColorField;
            }
            set {
                this.backColorField = value;
                this.RaisePropertyChanged("BackColor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("X");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("Y");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NonWorkingHours : BO {
        
        private int idField;
        
        private int teamMemberIdField;
        
        private System.DateTime dayField;
        
        private decimal hoursField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TeamMemberId {
            get {
                return this.teamMemberIdField;
            }
            set {
                this.teamMemberIdField = value;
                this.RaisePropertyChanged("TeamMemberId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime Day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
                this.RaisePropertyChanged("Day");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Hours {
            get {
                return this.hoursField;
            }
            set {
                this.hoursField = value;
                this.RaisePropertyChanged("Hours");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TeamMember : BO {
        
        private int idField;
        
        private string nameField;
        
        private string userNameField;
        
        private decimal focusFactorField;
        
        private decimal availabilityFactorField;
        
        private decimal normalWorkingHoursField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal FocusFactor {
            get {
                return this.focusFactorField;
            }
            set {
                this.focusFactorField = value;
                this.RaisePropertyChanged("FocusFactor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal AvailabilityFactor {
            get {
                return this.availabilityFactorField;
            }
            set {
                this.availabilityFactorField = value;
                this.RaisePropertyChanged("AvailabilityFactor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal NormalWorkingHours {
            get {
                return this.normalWorkingHoursField;
            }
            set {
                this.normalWorkingHoursField = value;
                this.RaisePropertyChanged("NormalWorkingHours");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Team : BO {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Panel : BO {
        
        private int idField;
        
        private int layoutIdField;
        
        private int stateIdField;
        
        private string titleField;
        
        private int storyTypeIdField;
        
        private int columnField;
        
        private int rowField;
        
        private int heigthField;
        
        private int widthField;
        
        private string stateNameField;
        
        private string storyTypeNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int LayoutId {
            get {
                return this.layoutIdField;
            }
            set {
                this.layoutIdField = value;
                this.RaisePropertyChanged("LayoutId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int StateId {
            get {
                return this.stateIdField;
            }
            set {
                this.stateIdField = value;
                this.RaisePropertyChanged("StateId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int StoryTypeId {
            get {
                return this.storyTypeIdField;
            }
            set {
                this.storyTypeIdField = value;
                this.RaisePropertyChanged("StoryTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Column {
            get {
                return this.columnField;
            }
            set {
                this.columnField = value;
                this.RaisePropertyChanged("Column");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
                this.RaisePropertyChanged("Row");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Heigth {
            get {
                return this.heigthField;
            }
            set {
                this.heigthField = value;
                this.RaisePropertyChanged("Heigth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("Width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string StateName {
            get {
                return this.stateNameField;
            }
            set {
                this.stateNameField = value;
                this.RaisePropertyChanged("StateName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string StoryTypeName {
            get {
                return this.storyTypeNameField;
            }
            set {
                this.storyTypeNameField = value;
                this.RaisePropertyChanged("StoryTypeName");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Layout : BO {
        
        private int idField;
        
        private int teamIdField;
        
        private string nameField;
        
        private int totalColumnsField;
        
        private int totalRowsField;
        
        private int fontSizeField;
        
        private int storyWidthField;
        
        private int storyHeightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TeamId {
            get {
                return this.teamIdField;
            }
            set {
                this.teamIdField = value;
                this.RaisePropertyChanged("TeamId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int TotalColumns {
            get {
                return this.totalColumnsField;
            }
            set {
                this.totalColumnsField = value;
                this.RaisePropertyChanged("TotalColumns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int TotalRows {
            get {
                return this.totalRowsField;
            }
            set {
                this.totalRowsField = value;
                this.RaisePropertyChanged("TotalRows");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int FontSize {
            get {
                return this.fontSizeField;
            }
            set {
                this.fontSizeField = value;
                this.RaisePropertyChanged("FontSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int StoryWidth {
            get {
                return this.storyWidthField;
            }
            set {
                this.storyWidthField = value;
                this.RaisePropertyChanged("StoryWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int StoryHeight {
            get {
                return this.storyHeightField;
            }
            set {
                this.storyHeightField = value;
                this.RaisePropertyChanged("StoryHeight");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StoryType : BO {
        
        private int idField;
        
        private string nameField;
        
        private int defaultBackColorField;
        
        private bool burnDownEnabledField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int DefaultBackColor {
            get {
                return this.defaultBackColorField;
            }
            set {
                this.defaultBackColorField = value;
                this.RaisePropertyChanged("DefaultBackColor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool BurnDownEnabled {
            get {
                return this.burnDownEnabledField;
            }
            set {
                this.burnDownEnabledField = value;
                this.RaisePropertyChanged("BurnDownEnabled");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class State : BO {
        
        private int idField;
        
        private string nameField;
        
        private bool isInitialField;
        
        private bool isFinalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsInitial {
            get {
                return this.isInitialField;
            }
            set {
                this.isInitialField = value;
                this.RaisePropertyChanged("IsInitial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsFinal {
            get {
                return this.isFinalField;
            }
            set {
                this.isFinalField = value;
                this.RaisePropertyChanged("IsFinal");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sprint : BO {
        
        private int idField;
        
        private int layoutIdField;
        
        private int teamIdField;
        
        private string nameField;
        
        private System.DateTime startDateField;
        
        private System.DateTime targetDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int LayoutId {
            get {
                return this.layoutIdField;
            }
            set {
                this.layoutIdField = value;
                this.RaisePropertyChanged("LayoutId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TeamId {
            get {
                return this.teamIdField;
            }
            set {
                this.teamIdField = value;
                this.RaisePropertyChanged("TeamId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime TargetDate {
            get {
                return this.targetDateField;
            }
            set {
                this.targetDateField = value;
                this.RaisePropertyChanged("TargetDate");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ScrumboardSoapChannel : ScrumBoard.ScrumboardService.ScrumboardSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScrumboardSoapClient : System.ServiceModel.ClientBase<ScrumBoard.ScrumboardService.ScrumboardSoap>, ScrumBoard.ScrumboardService.ScrumboardSoap {
        
        public ScrumboardSoapClient() {
        }
        
        public ScrumboardSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScrumboardSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScrumboardSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScrumboardSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int StoryInsert(int sprintId, string externalId, int storyTypeId, int statusId, string description, int estimate, int backcolor, int x, int y, string tag) {
            return base.Channel.StoryInsert(sprintId, externalId, storyTypeId, statusId, description, estimate, backcolor, x, y, tag);
        }
        
        public void StoryUpdateDetails(int id, int sprintId, string externalId, int storyTypeId, int statusId, string description, int estimate, int backcolor, int x, int y, string tag) {
            base.Channel.StoryUpdateDetails(id, sprintId, externalId, storyTypeId, statusId, description, estimate, backcolor, x, y, tag);
        }
        
        public void StoryUpdateStatus(int id, int statusId) {
            base.Channel.StoryUpdateStatus(id, statusId);
        }
        
        public void StoryRemove(int id) {
            base.Channel.StoryRemove(id);
        }
        
        public ScrumBoard.ScrumboardService.Story StoryGetByExternalId(int sprintId, string externalId) {
            return base.Channel.StoryGetByExternalId(sprintId, externalId);
        }
        
        public Story[] StoryGetSprintStories(int sprintId) {
            return base.Channel.StoryGetSprintStories(sprintId);
        }
        
        public Story[] StoryGetPanelStories(int sprintId, int storyTypeId, int statusId) {
            return base.Channel.StoryGetPanelStories(sprintId, storyTypeId, statusId);
        }
        
        public int SprintInsert(int layoutId, int teamId, string name, System.DateTime startDate, System.DateTime target) {
            return base.Channel.SprintInsert(layoutId, teamId, name, startDate, target);
        }
        
        public void SprintUpdate(int id, int layoutId, int teamId, string name, System.DateTime startDate, System.DateTime target) {
            base.Channel.SprintUpdate(id, layoutId, teamId, name, startDate, target);
        }
        
        public ScrumBoard.ScrumboardService.Sprint SprintGet(int sprintId) {
            return base.Channel.SprintGet(sprintId);
        }
        
        public Sprint[] SprintSelectAll() {
            return base.Channel.SprintSelectAll();
        }
        
        public Sprint[] SprintSelectByTeam(int teamId) {
            return base.Channel.SprintSelectByTeam(teamId);
        }
        
        public State[] StateSelectAll() {
            return base.Channel.StateSelectAll();
        }
        
        public ScrumBoard.ScrumboardService.State StateGet(int id) {
            return base.Channel.StateGet(id);
        }
        
        public StoryType[] StoryTypeSelectAll() {
            return base.Channel.StoryTypeSelectAll();
        }
        
        public ScrumBoard.ScrumboardService.StoryType StoryTypeGet(int id) {
            return base.Channel.StoryTypeGet(id);
        }
        
        public Layout[] LayoutSelectAll() {
            return base.Channel.LayoutSelectAll();
        }
        
        public int LayoutInsert(string name, int totalColumns, int totalRows, int fontSize, int storyWidth, int storyHeight) {
            return base.Channel.LayoutInsert(name, totalColumns, totalRows, fontSize, storyWidth, storyHeight);
        }
        
        public void LayoutUpdate(int id, string name, int totalColumns, int totalRows, int fontSize, int storyWidth, int storyHeight) {
            base.Channel.LayoutUpdate(id, name, totalColumns, totalRows, fontSize, storyWidth, storyHeight);
        }
        
        public ScrumBoard.ScrumboardService.Layout LayoutGet(int id) {
            return base.Channel.LayoutGet(id);
        }
        
        public Panel[] LayoutPanelSelectByLayout(int layoutId) {
            return base.Channel.LayoutPanelSelectByLayout(layoutId);
        }
        
        public ScrumBoard.ScrumboardService.Panel LayoutPanelGet(int id) {
            return base.Channel.LayoutPanelGet(id);
        }
        
        public int LayoutPanelInsert(int layoutId, int stateId, string title, int storyTypeId, int column, int row, int height, int width) {
            return base.Channel.LayoutPanelInsert(layoutId, stateId, title, storyTypeId, column, row, height, width);
        }
        
        public void LayoutPanelUpdate(int id, int stateId, string title, int storyTypeId, int column, int row, int height, int width) {
            base.Channel.LayoutPanelUpdate(id, stateId, title, storyTypeId, column, row, height, width);
        }
        
        public void LayoutPanelRemove(int id) {
            base.Channel.LayoutPanelRemove(id);
        }
        
        public Team[] TeamSelectAll() {
            return base.Channel.TeamSelectAll();
        }
        
        public ScrumBoard.ScrumboardService.Team TeamGet(int id) {
            return base.Channel.TeamGet(id);
        }
        
        public int TeamInsert(string name) {
            return base.Channel.TeamInsert(name);
        }
        
        public void TeamUpdate(int id, string name) {
            base.Channel.TeamUpdate(id, name);
        }
        
        public void TeamRemove(int id) {
            base.Channel.TeamRemove(id);
        }
        
        public void TeamAssignMember(int teamId, int teamMemberId) {
            base.Channel.TeamAssignMember(teamId, teamMemberId);
        }
        
        public void TeamDeassignMember(int teamId, int teamMemberId) {
            base.Channel.TeamDeassignMember(teamId, teamMemberId);
        }
        
        public TeamMember[] TeamMemberSelectAll() {
            return base.Channel.TeamMemberSelectAll();
        }
        
        public TeamMember[] TeamMemberSelectByTeam(int teamId) {
            return base.Channel.TeamMemberSelectByTeam(teamId);
        }
        
        public ScrumBoard.ScrumboardService.TeamMember TeamMemberGet(int id) {
            return base.Channel.TeamMemberGet(id);
        }
        
        public int TeamMemberInsert(string name, string userName, string focusFactor, string availabilityFactor, string normalWorkingHours) {
            return base.Channel.TeamMemberInsert(name, userName, focusFactor, availabilityFactor, normalWorkingHours);
        }
        
        public void TeamMemberUpdate(int id, string name, string userName, string focusFactor, string availabilityFactor, string normalWorkingHours) {
            base.Channel.TeamMemberUpdate(id, name, userName, focusFactor, availabilityFactor, normalWorkingHours);
        }
        
        public void TeamMemberRemove(int id) {
            base.Channel.TeamMemberRemove(id);
        }
        
        public NonWorkingHours[] TeamGetNonWorkingHours(int teamMemberId) {
            return base.Channel.TeamGetNonWorkingHours(teamMemberId);
        }
        
        public NonWorkingHours[] TeamGetNonWorkingHoursAtDay(int teamMemberId, System.DateTime day) {
            return base.Channel.TeamGetNonWorkingHoursAtDay(teamMemberId, day);
        }
        
        public int TeamInsertNonWorkingHours(int teamMemberId, System.DateTime day, string hours) {
            return base.Channel.TeamInsertNonWorkingHours(teamMemberId, day, hours);
        }
        
        public void TeamUpdateNonWorkingHours(int id, int teamMemberId, System.DateTime day, string hours) {
            base.Channel.TeamUpdateNonWorkingHours(id, teamMemberId, day, hours);
        }
        
        public void TeamRemoveNonWorkingHours(int id) {
            base.Channel.TeamRemoveNonWorkingHours(id);
        }
        
        public int TodoInsert(int storyId, string description, int estimate, int backcolor, int x, int y) {
            return base.Channel.TodoInsert(storyId, description, estimate, backcolor, x, y);
        }
        
        public void TodoUpdate(int id, int storyId, string description, int estimate, int backcolor, int x, int y) {
            base.Channel.TodoUpdate(id, storyId, description, estimate, backcolor, x, y);
        }
        
        public void TodoRemove(int id) {
            base.Channel.TodoRemove(id);
        }
        
        public ScrumBoard.ScrumboardService.Todo TodoGet(int id) {
            return base.Channel.TodoGet(id);
        }
        
        public Todo[] TodoSelect(int storyId) {
            return base.Channel.TodoSelect(storyId);
        }
    }
}
