//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScrumBoard.ScrumboardService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScrumboardService.ScrumboardSoap")]
    public interface ScrumboardSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoryInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Story StoryInsert(int sprintId, string externalId, int storyTypeId, int statusId, string description, int estimate, int backcolor, int x, int y, string tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoryUpdateDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Story StoryUpdateDetails(int id, int sprintId, string externalId, int storyTypeId, int statusId, string description, int estimate, int backcolor, int x, int y, string tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoryRemove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Story StoryRemove(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoryGetSprintStories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Story[] StoryGetSprintStories(int sprintId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoryGetSprintModifiedStories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Story[] StoryGetSprintModifiedStories(int sprintId, System.DateTime modified);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SprintInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        int SprintInsert(int layoutId, int teamId, string name, System.DateTime startDate, System.DateTime target, int velocity, int focusFactor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SprintUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void SprintUpdate(int id, int layoutId, int teamId, string name, System.DateTime startDate, System.DateTime target, int velocity, int focusFactor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SprintGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Sprint SprintGet(int sprintId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SprintSelectAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Sprint[] SprintSelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SprintSelectByTeam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Sprint[] SprintSelectByTeam(int teamId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StateSelectAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.State[] StateSelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StateGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.State StateGet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StateInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        int StateInsert(string name, bool isInitial, bool isFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StateUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void StateUpdate(int id, string name, bool isInitial, bool isFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoryTypeSelectAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.StoryType[] StoryTypeSelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoryTypeGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.StoryType StoryTypeGet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoryTypeInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        int StoryTypeInsert(string name, int defaultBackColor, bool isBurnDownEnabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoryTypeUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void StoryTypeUpdate(int id, string name, int defaultBackColor, bool isBurnDownEnabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayoutSelectAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Layout[] LayoutSelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayoutInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        int LayoutInsert(string name, int totalColumns, int totalRows, int fontSize, int storyWidth, int storyHeight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayoutUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void LayoutUpdate(int id, string name, int totalColumns, int totalRows, int fontSize, int storyWidth, int storyHeight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayoutGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Layout LayoutGet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayoutPanelSelectByLayout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Panel[] LayoutPanelSelectByLayout(int layoutId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayoutPanelGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Panel LayoutPanelGet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayoutPanelInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        int LayoutPanelInsert(int layoutId, int stateId, string title, int storyTypeId, int column, int row, int height, int width);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayoutPanelUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void LayoutPanelUpdate(int id, int stateId, string title, int storyTypeId, int column, int row, int height, int width);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayoutPanelRemove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void LayoutPanelRemove(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamSelectAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Team[] TeamSelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Team TeamGet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        int TeamInsert(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void TeamUpdate(int id, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TeamRemove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        void TeamRemove(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TodoInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Todo TodoInsert(int storyId, string description, int estimate, int backcolor, int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TodoUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Todo TodoUpdate(int id, int storyId, string description, int estimate, int backcolor, int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TodoRemove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Todo TodoRemove(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TodoGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Todo TodoGet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TodoSelect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BO))]
        ScrumBoard.ScrumboardService.Todo[] TodoSelect(int storyId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Story : BO {
        
        private int idField;
        
        private string externalIdField;
        
        private int sprintIdField;
        
        private int storyTypeIdField;
        
        private string descriptionField;
        
        private int estimateField;
        
        private int statusIdField;
        
        private int xField;
        
        private int yField;
        
        private int backColorField;
        
        private string tagField;
        
        private bool isRemovedField;
        
        private System.DateTime createdField;
        
        private System.DateTime closedDateField;
        
        private System.DateTime modifiedField;
        
        private bool isBurndownEnabledField;
        
        private Todo[] todosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ExternalId {
            get {
                return this.externalIdField;
            }
            set {
                this.externalIdField = value;
                this.RaisePropertyChanged("ExternalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int SprintId {
            get {
                return this.sprintIdField;
            }
            set {
                this.sprintIdField = value;
                this.RaisePropertyChanged("SprintId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int StoryTypeId {
            get {
                return this.storyTypeIdField;
            }
            set {
                this.storyTypeIdField = value;
                this.RaisePropertyChanged("StoryTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Estimate {
            get {
                return this.estimateField;
            }
            set {
                this.estimateField = value;
                this.RaisePropertyChanged("Estimate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int StatusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
                this.RaisePropertyChanged("StatusId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("X");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("Y");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int BackColor {
            get {
                return this.backColorField;
            }
            set {
                this.backColorField = value;
                this.RaisePropertyChanged("BackColor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("Tag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool IsRemoved {
            get {
                return this.isRemovedField;
            }
            set {
                this.isRemovedField = value;
                this.RaisePropertyChanged("IsRemoved");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("Created");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public System.DateTime ClosedDate {
            get {
                return this.closedDateField;
            }
            set {
                this.closedDateField = value;
                this.RaisePropertyChanged("ClosedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public System.DateTime Modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
                this.RaisePropertyChanged("Modified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool IsBurndownEnabled {
            get {
                return this.isBurndownEnabledField;
            }
            set {
                this.isBurndownEnabledField = value;
                this.RaisePropertyChanged("IsBurndownEnabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        public Todo[] Todos {
            get {
                return this.todosField;
            }
            set {
                this.todosField = value;
                this.RaisePropertyChanged("Todos");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Todo : BO {
        
        private int idField;
        
        private int storyIdField;
        
        private string descriptionField;
        
        private int estimateField;
        
        private int backColorField;
        
        private int xField;
        
        private int yField;
        
        private System.DateTime modifiedField;
        
        private bool isRemovedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int StoryId {
            get {
                return this.storyIdField;
            }
            set {
                this.storyIdField = value;
                this.RaisePropertyChanged("StoryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Estimate {
            get {
                return this.estimateField;
            }
            set {
                this.estimateField = value;
                this.RaisePropertyChanged("Estimate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int BackColor {
            get {
                return this.backColorField;
            }
            set {
                this.backColorField = value;
                this.RaisePropertyChanged("BackColor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("X");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("Y");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime Modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
                this.RaisePropertyChanged("Modified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool IsRemoved {
            get {
                return this.isRemovedField;
            }
            set {
                this.isRemovedField = value;
                this.RaisePropertyChanged("IsRemoved");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Team))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Panel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Layout))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StoryType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(State))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Sprint))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Todo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Story))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class BO : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Team : BO {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Panel : BO {
        
        private int idField;
        
        private int layoutIdField;
        
        private int stateIdField;
        
        private string titleField;
        
        private int storyTypeIdField;
        
        private int columnField;
        
        private int rowField;
        
        private int heigthField;
        
        private int widthField;
        
        private string stateNameField;
        
        private string storyTypeNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int LayoutId {
            get {
                return this.layoutIdField;
            }
            set {
                this.layoutIdField = value;
                this.RaisePropertyChanged("LayoutId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int StateId {
            get {
                return this.stateIdField;
            }
            set {
                this.stateIdField = value;
                this.RaisePropertyChanged("StateId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int StoryTypeId {
            get {
                return this.storyTypeIdField;
            }
            set {
                this.storyTypeIdField = value;
                this.RaisePropertyChanged("StoryTypeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Column {
            get {
                return this.columnField;
            }
            set {
                this.columnField = value;
                this.RaisePropertyChanged("Column");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
                this.RaisePropertyChanged("Row");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Heigth {
            get {
                return this.heigthField;
            }
            set {
                this.heigthField = value;
                this.RaisePropertyChanged("Heigth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("Width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string StateName {
            get {
                return this.stateNameField;
            }
            set {
                this.stateNameField = value;
                this.RaisePropertyChanged("StateName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string StoryTypeName {
            get {
                return this.storyTypeNameField;
            }
            set {
                this.storyTypeNameField = value;
                this.RaisePropertyChanged("StoryTypeName");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Layout : BO {
        
        private int idField;
        
        private int teamIdField;
        
        private string nameField;
        
        private int totalColumnsField;
        
        private int totalRowsField;
        
        private int fontSizeField;
        
        private int storyWidthField;
        
        private int storyHeightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TeamId {
            get {
                return this.teamIdField;
            }
            set {
                this.teamIdField = value;
                this.RaisePropertyChanged("TeamId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int TotalColumns {
            get {
                return this.totalColumnsField;
            }
            set {
                this.totalColumnsField = value;
                this.RaisePropertyChanged("TotalColumns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int TotalRows {
            get {
                return this.totalRowsField;
            }
            set {
                this.totalRowsField = value;
                this.RaisePropertyChanged("TotalRows");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int FontSize {
            get {
                return this.fontSizeField;
            }
            set {
                this.fontSizeField = value;
                this.RaisePropertyChanged("FontSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int StoryWidth {
            get {
                return this.storyWidthField;
            }
            set {
                this.storyWidthField = value;
                this.RaisePropertyChanged("StoryWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int StoryHeight {
            get {
                return this.storyHeightField;
            }
            set {
                this.storyHeightField = value;
                this.RaisePropertyChanged("StoryHeight");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StoryType : BO {
        
        private int idField;
        
        private string nameField;
        
        private int defaultBackColorField;
        
        private bool burnDownEnabledField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int DefaultBackColor {
            get {
                return this.defaultBackColorField;
            }
            set {
                this.defaultBackColorField = value;
                this.RaisePropertyChanged("DefaultBackColor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool BurnDownEnabled {
            get {
                return this.burnDownEnabledField;
            }
            set {
                this.burnDownEnabledField = value;
                this.RaisePropertyChanged("BurnDownEnabled");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class State : BO {
        
        private int idField;
        
        private string nameField;
        
        private bool isInitialField;
        
        private bool isFinalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsInitial {
            get {
                return this.isInitialField;
            }
            set {
                this.isInitialField = value;
                this.RaisePropertyChanged("IsInitial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsFinal {
            get {
                return this.isFinalField;
            }
            set {
                this.isFinalField = value;
                this.RaisePropertyChanged("IsFinal");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sprint : BO {
        
        private int idField;
        
        private int layoutIdField;
        
        private int teamIdField;
        
        private string nameField;
        
        private System.DateTime startDateField;
        
        private System.DateTime targetDateField;
        
        private int velocityField;
        
        private int focusFactorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int LayoutId {
            get {
                return this.layoutIdField;
            }
            set {
                this.layoutIdField = value;
                this.RaisePropertyChanged("LayoutId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TeamId {
            get {
                return this.teamIdField;
            }
            set {
                this.teamIdField = value;
                this.RaisePropertyChanged("TeamId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime TargetDate {
            get {
                return this.targetDateField;
            }
            set {
                this.targetDateField = value;
                this.RaisePropertyChanged("TargetDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Velocity {
            get {
                return this.velocityField;
            }
            set {
                this.velocityField = value;
                this.RaisePropertyChanged("Velocity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int FocusFactor {
            get {
                return this.focusFactorField;
            }
            set {
                this.focusFactorField = value;
                this.RaisePropertyChanged("FocusFactor");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ScrumboardSoapChannel : ScrumBoard.ScrumboardService.ScrumboardSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScrumboardSoapClient : System.ServiceModel.ClientBase<ScrumBoard.ScrumboardService.ScrumboardSoap>, ScrumBoard.ScrumboardService.ScrumboardSoap {
        
        public ScrumboardSoapClient() {
        }
        
        public ScrumboardSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScrumboardSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScrumboardSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScrumboardSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ScrumBoard.ScrumboardService.Story StoryInsert(int sprintId, string externalId, int storyTypeId, int statusId, string description, int estimate, int backcolor, int x, int y, string tag) {
            return base.Channel.StoryInsert(sprintId, externalId, storyTypeId, statusId, description, estimate, backcolor, x, y, tag);
        }
        
        public ScrumBoard.ScrumboardService.Story StoryUpdateDetails(int id, int sprintId, string externalId, int storyTypeId, int statusId, string description, int estimate, int backcolor, int x, int y, string tag) {
            return base.Channel.StoryUpdateDetails(id, sprintId, externalId, storyTypeId, statusId, description, estimate, backcolor, x, y, tag);
        }
        
        public ScrumBoard.ScrumboardService.Story StoryRemove(int id) {
            return base.Channel.StoryRemove(id);
        }
        
        public ScrumBoard.ScrumboardService.Story[] StoryGetSprintStories(int sprintId) {
            return base.Channel.StoryGetSprintStories(sprintId);
        }
        
        public ScrumBoard.ScrumboardService.Story[] StoryGetSprintModifiedStories(int sprintId, System.DateTime modified) {
            return base.Channel.StoryGetSprintModifiedStories(sprintId, modified);
        }
        
        public int SprintInsert(int layoutId, int teamId, string name, System.DateTime startDate, System.DateTime target, int velocity, int focusFactor) {
            return base.Channel.SprintInsert(layoutId, teamId, name, startDate, target, velocity, focusFactor);
        }
        
        public void SprintUpdate(int id, int layoutId, int teamId, string name, System.DateTime startDate, System.DateTime target, int velocity, int focusFactor) {
            base.Channel.SprintUpdate(id, layoutId, teamId, name, startDate, target, velocity, focusFactor);
        }
        
        public ScrumBoard.ScrumboardService.Sprint SprintGet(int sprintId) {
            return base.Channel.SprintGet(sprintId);
        }
        
        public ScrumBoard.ScrumboardService.Sprint[] SprintSelectAll() {
            return base.Channel.SprintSelectAll();
        }
        
        public ScrumBoard.ScrumboardService.Sprint[] SprintSelectByTeam(int teamId) {
            return base.Channel.SprintSelectByTeam(teamId);
        }
        
        public ScrumBoard.ScrumboardService.State[] StateSelectAll() {
            return base.Channel.StateSelectAll();
        }
        
        public ScrumBoard.ScrumboardService.State StateGet(int id) {
            return base.Channel.StateGet(id);
        }
        
        public int StateInsert(string name, bool isInitial, bool isFinal) {
            return base.Channel.StateInsert(name, isInitial, isFinal);
        }
        
        public void StateUpdate(int id, string name, bool isInitial, bool isFinal) {
            base.Channel.StateUpdate(id, name, isInitial, isFinal);
        }
        
        public ScrumBoard.ScrumboardService.StoryType[] StoryTypeSelectAll() {
            return base.Channel.StoryTypeSelectAll();
        }
        
        public ScrumBoard.ScrumboardService.StoryType StoryTypeGet(int id) {
            return base.Channel.StoryTypeGet(id);
        }
        
        public int StoryTypeInsert(string name, int defaultBackColor, bool isBurnDownEnabled) {
            return base.Channel.StoryTypeInsert(name, defaultBackColor, isBurnDownEnabled);
        }
        
        public void StoryTypeUpdate(int id, string name, int defaultBackColor, bool isBurnDownEnabled) {
            base.Channel.StoryTypeUpdate(id, name, defaultBackColor, isBurnDownEnabled);
        }
        
        public ScrumBoard.ScrumboardService.Layout[] LayoutSelectAll() {
            return base.Channel.LayoutSelectAll();
        }
        
        public int LayoutInsert(string name, int totalColumns, int totalRows, int fontSize, int storyWidth, int storyHeight) {
            return base.Channel.LayoutInsert(name, totalColumns, totalRows, fontSize, storyWidth, storyHeight);
        }
        
        public void LayoutUpdate(int id, string name, int totalColumns, int totalRows, int fontSize, int storyWidth, int storyHeight) {
            base.Channel.LayoutUpdate(id, name, totalColumns, totalRows, fontSize, storyWidth, storyHeight);
        }
        
        public ScrumBoard.ScrumboardService.Layout LayoutGet(int id) {
            return base.Channel.LayoutGet(id);
        }
        
        public ScrumBoard.ScrumboardService.Panel[] LayoutPanelSelectByLayout(int layoutId) {
            return base.Channel.LayoutPanelSelectByLayout(layoutId);
        }
        
        public ScrumBoard.ScrumboardService.Panel LayoutPanelGet(int id) {
            return base.Channel.LayoutPanelGet(id);
        }
        
        public int LayoutPanelInsert(int layoutId, int stateId, string title, int storyTypeId, int column, int row, int height, int width) {
            return base.Channel.LayoutPanelInsert(layoutId, stateId, title, storyTypeId, column, row, height, width);
        }
        
        public void LayoutPanelUpdate(int id, int stateId, string title, int storyTypeId, int column, int row, int height, int width) {
            base.Channel.LayoutPanelUpdate(id, stateId, title, storyTypeId, column, row, height, width);
        }
        
        public void LayoutPanelRemove(int id) {
            base.Channel.LayoutPanelRemove(id);
        }
        
        public ScrumBoard.ScrumboardService.Team[] TeamSelectAll() {
            return base.Channel.TeamSelectAll();
        }
        
        public ScrumBoard.ScrumboardService.Team TeamGet(int id) {
            return base.Channel.TeamGet(id);
        }
        
        public int TeamInsert(string name) {
            return base.Channel.TeamInsert(name);
        }
        
        public void TeamUpdate(int id, string name) {
            base.Channel.TeamUpdate(id, name);
        }
        
        public void TeamRemove(int id) {
            base.Channel.TeamRemove(id);
        }
        
        public ScrumBoard.ScrumboardService.Todo TodoInsert(int storyId, string description, int estimate, int backcolor, int x, int y) {
            return base.Channel.TodoInsert(storyId, description, estimate, backcolor, x, y);
        }
        
        public ScrumBoard.ScrumboardService.Todo TodoUpdate(int id, int storyId, string description, int estimate, int backcolor, int x, int y) {
            return base.Channel.TodoUpdate(id, storyId, description, estimate, backcolor, x, y);
        }
        
        public ScrumBoard.ScrumboardService.Todo TodoRemove(int id) {
            return base.Channel.TodoRemove(id);
        }
        
        public ScrumBoard.ScrumboardService.Todo TodoGet(int id) {
            return base.Channel.TodoGet(id);
        }
        
        public ScrumBoard.ScrumboardService.Todo[] TodoSelect(int storyId) {
            return base.Channel.TodoSelect(storyId);
        }
    }
}
